name: Setup Python Environment
description: Setup Python and install project dependencies

inputs:
  python-version:
    default: "3.10"
    description: Python version number to use.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}

    - name: Install project and dependencies
      shell: bash
      run: uv sync
