name: Setup Python Environment
description: Setup Python and install dependencies with Poetry
runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup python 3.7
    uses: actions/setup-python@v2
    with:
      python-version: 3.7

  - name: Setup Poetry
    uses: Gr1N/setup-poetry@v7

  - name: Cache dependencies
    uses: actions/cache@v2
    with:
      path: ~/.cache/pypoetry/virtualenvs
      key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

  - name: Cache pre-commit
    uses: actions/cache@v2
    with:
      path: ~/.cache/pre-commit
      key: pre-commit|${{ runner.os }}|python-${{ steps.setup-python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

  - name: Install package
    run: |
      poetry install
